# Generated by Django 5.1.6 on 2025-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
