# Generated by Django 5.1.6 on 2025-02-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0003_remove_mediafile_user_mediafile_media_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='media_author',
            new_name='user',
        ),
    ]
