# Generated by Django 5.1.6 on 2025-02-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0004_rename_media_author_mediafile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Upload Document'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Your Notification'},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('pdf', 'Pdf'), ('image', 'Image')], default='image', max_length=10),
        ),
    ]
