# Generated by Django 5.1.6 on 2025-02-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0005_alter_mediafile_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Uploaded Document'},
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='content',
        ),
    ]
